# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97149e8e3a5a5d6cb49974246678e06885b04c31b2a6ca4078733b2dfefdacca69d6acec75c58eaf921a3b8c1fd1f2d5405bdf6771e65deba1270901691d0af3

test:
  secret_key_base: b76aad78f4b5a0f332c5f4a52d23cc0c14b59183ecc529013d62491436926a101d0fed751f3f90c54a4018f977901a4e384b8bb672a270677d9147c807070bf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
